website/cart/urls.py
from django.urls import path

from .views import APICart
from .views import DetailCart

app_name = "cart"

urlpatterns = [
    path("detail/", DetailCart.as_view(), name="detail"),
    path("api/", APICart.as_view(), name="api"),
]

website/custom_auth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from .views import LogInView
from .views import LogOutView
from .views import PersonalCabinet
from .views import ProfileOrdersView
from .views import ProfileView
from .views import RegisterView
from .views import ResetCashView
from .views import SettingsChangeView
from .views import SettingsPageView
from .views import UserPasswordResetConfirmView
from .views import ViewedListView

app_name = "custom_auth"

urlpatterns = [
    path("login/", LogInView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("settings/", SettingsPageView.as_view(), name="settings"),
    path("settings/change/", SettingsChangeView.as_view(), name="settings_change"),
    path("cashing/", ResetCashView.as_view(), name="cashing"),
    path("viewed/", ViewedListView.as_view(), name="viewed-list"),
    path("personal_cabinet/", PersonalCabinet.as_view(), name="personal-cabinet"),
    path("profile_orders/", ProfileOrdersView.as_view(), name="profile-orders"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="custom_auth/password_reset.html",
            email_template_name="account/password_reset_email.html",
            success_url=reverse_lazy("account:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="custom_auth/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(template_name="custom_auth/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

website/website/urls.py
from itertools import product

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView

# def trigger_error(request):
#     division_by_zero = 1 / 0

urlpatterns = i18n_patterns(
    # Standard URL
    path("", include("core.urls", namespace="default")),
    path("admin/", admin.site.urls),
    path("account/", include("custom_auth.urls")),
    path("order/", include("order.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("discount/", include("discount.urls")),
    path("payment/", include("payment.urls")),
    # API
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/v1/", include("review.urls")),
    # path('sentry-debug/', trigger_error),
) + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

website/custom_auth/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager
from .utils import profile_photo_directory_path
from .utils import validate_avatar_size


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    Изменённая модель пользователя, с которым завязаны все действия по
    регистрации, аутентификации и авторизации.

    Attributes:
        login: login пользователя;
        email: email пользователя;
        created_at: дата регистрации пользователя;
        is_staff: Логическое значение - является ли пользователь администратором;
        is_active: Логическое значение - для "мягкого" удаления пользователя.
    """

    login = models.CharField(max_length=50, unique=True, verbose_name=_("Login"))
    email = models.EmailField(unique=True, verbose_name=_("Email"), db_index=True)
    username = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, verbose_name=_("Created at"))
    is_staff = models.BooleanField(
        default=False,
        verbose_name=_("Staff status"),
        help_text="Designates whether the user can log into this admin site.",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Active"),
        help_text="Designates whether this user should be treated as active."
        " Unselect this instead of deleting accounts.",
    )
    birthday = models.DateField(
        null=True,
        blank=True,
        verbose_name=_("Birthday"),
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["login"]

    objects = CustomUserManager()

    class Meta:
        app_label = "custom_auth"
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        ordering = ("login",)

    def __str__(self):
        """Возвращаем никнейм пользователя, если он имеется"""
        return self.login if self.login else "Anonymous"


class Profile(models.Model):
    """
    Модель для дополнительной информации пользователя.

    Attributes:
        user: связь к пользователю по типу связи один-к-одному
        first_name: имя пользователя;
        last_name: фамилия пользователя;
        patronymic: отчество (при наличии)
        address: адрес пользователя;
        phone: номер телефона пользователя;
        photo: фото/аватар пользователя.
    """

    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name=_("User"),
        related_name="profile",
    )
    first_name = models.CharField(max_length=50, null=True, blank=True, verbose_name=_("Firstname"))
    last_name = models.CharField(max_length=50, null=True, blank=True, verbose_name=_("Lastname"))
    patronymic = models.CharField(max_length=50, null=True, blank=True, verbose_name=_("Patronymic"))
    address = models.CharField(max_length=200, null=True, blank=True, verbose_name=_("Address"))
    phone = models.CharField(
        unique=True,
        max_length=18,
        null=True,
        blank=True,
    )
    photo = models.ImageField(
        upload_to=profile_photo_directory_path,
        verbose_name=_("Photo"),
        validators=[validate_avatar_size],
        null=True,
        blank=True,
    )

    class Meta:
        app_label = "custom_auth"
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")
        ordering = (
            "first_name",
            "last_name",
        )

    def __str__(self):
        """Возвращаем имя профиля, если оно имеется"""
        return self.first_name if self.first_name else f"Имя профиля №{self.pk}"

website/order/models.py
from catalog.models import Delivery
from catalog.models import Payment
from catalog.models import Product
from catalog.models import Seller
from custom_auth.models import Profile
from django.db import models
from django.db.models import PROTECT
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from website import settings


class Order(models.Model):
    """
    Модель для хранения информации о заказах пользователей.

    Этот класс представляет заказ пользователя, содержащий информацию о доставке, статусе, стоимости и других деталях.
    Каждый заказ может быть в одном из нескольких состояний (например, в процессе обработки или доставлен).
    Каждый заказ связан с конкретным пользователем.

    Атрибуты:
        user (ForeignKey): Ссылка на пользователя, сделавшего заказ.
        delivery_city (CharField): Город, в который будет доставлен заказ.
        delivery_address (TextField): Адрес для доставки.
        recipient_phone (CharField): Телефон получателя заказа.
        recipient_email (EmailField): Email получателя заказа.
        status (CharField): Статус заказа, выбирается из заранее заданных вариантов.
        archived (BooleanField): Указывает, является ли заказ архивированным.
        created_at (DateTimeField): Дата и время создания заказа.
        updated_at (DateTimeField): Дата и время последнего обновления заказа.
        total_price (DecimalField): Общая стоимость заказа.
        comment (TextField): Комментарий к заказу.
        delivery_price (ForeignKey): Ссылка на цену доставки для этого заказа.

    Метаданные:
        уникальность данных не гарантируется, но статус заказа можно изменять по мере обработки.
    """

    PENDING = "OP"
    PROCESSING = "PR"
    SHIPPED = "SH"
    DELIVERED = "DL"
    CANCELLED = "CN"

    STATUS_CHOICES = (
        (PENDING, _("The order is awaiting processing")),
        (PROCESSING, _("The order is in progress")),
        (SHIPPED, _("The order has been sent")),
        (DELIVERED, _("The order has been delivered")),
        (CANCELLED, _("The order has been cancelled")),
    )

    PAID = "PD"
    PARTLY_PAID = "PP"
    UNPAID = "UN"

    PAID_CHOICES = (
        (PAID, _("The order has been paid for")),
        (PARTLY_PAID, _("The order has been partially paid for")),
        (UNPAID, _("The order has not been paid")),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_("User"), related_name="orders"
    )
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    delivery_city = models.CharField(max_length=255, verbose_name=_("Delivery city"))
    delivery_address = models.TextField(max_length=500, verbose_name=_("Delivery address"))
    recipient_phone = models.CharField(max_length=15, verbose_name=_("Recipient phone number"))
    recipient_email = models.EmailField(verbose_name=_("Recipient email"))
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=PENDING)
    archived = models.BooleanField(default=False, verbose_name=_("Archived"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Updated at"))
    total_price = models.DecimalField(null=False, max_digits=10, decimal_places=2, verbose_name=_("Total price"))
    comment = models.TextField(max_length=1000, null=True, blank=True, verbose_name=_("Comment"))
    delivery_price = models.ForeignKey("DeliveryPrice", on_delete=PROTECT, verbose_name=_("Delivery price"))
    paid_status = models.CharField(max_length=2, choices=PAID_CHOICES, default=UNPAID)

    def __str__(self):
        return f"Order: {self.id}"

    def get_absolute_url(self):
        return reverse("order:order_detail", kwargs={"pk": self.id})


class OrderItem(models.Model):
    """
    Модель для хранения информации о товаре в рамках заказа.

    Этот класс представляет товар, добавленный в заказ. Каждый товар имеет ссылку на продавца, тип доставки, способ оплаты, а также
    информацию о количестве и цене. Один заказ может содержать несколько товаров.

    Атрибуты:
        seller (ForeignKey): Ссылка на продавца товара.
        product (ForeignKey): Ссылка на товар, добавленный в заказ.
        quantity (IntegerField): Количество товара в заказе.
        price (DecimalField): Цена товара в заказе.
        delivery (ForeignKey): Ссылка на тип доставки для товара.
        payment_type (ForeignKey): Ссылка на способ оплаты для товара.
        order (ForeignKey): Ссылка на заказ, к которому относится товар.
        active (BooleanField): Указывает, активен ли товар в заказе.
        payment_status (BooleanField): Указывает, оплачен ли товар.

    Метаданные:
        Один заказ может содержать несколько товаров. Связь с заказом через `related_name="order_items"`.
    """

    seller = models.ForeignKey(Seller, on_delete=models.PROTECT, verbose_name=_("Seller"))
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name=_("Product"))
    quantity = models.IntegerField(verbose_name=_("Quantity"))
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("Price"), default=0.00)
    delivery = models.ForeignKey(Delivery, on_delete=models.PROTECT, verbose_name=_("Delivery"))
    payment_type = models.ForeignKey(Payment, on_delete=models.PROTECT, verbose_name=_("Payment type"))
    order = models.ForeignKey(Order, related_name="order_items", on_delete=models.PROTECT, verbose_name=_("Order"))
    active = models.BooleanField(default=True, verbose_name=_("Active"))
    payment_status = models.BooleanField(default=False, verbose_name=_("Payment status"))
    receipt_url = models.CharField(max_length=255, null=False, default="", verbose_name=_("Receipt url"))

    def __str__(self):
        return f"{self.product}, {self.seller}, {self.quantity}, {self.price}"


class DeliveryPrice(models.Model):
    """
    Модель для хранения информации о типах доставки и их ценах.

    Этот класс представляет различные варианты доставки с ценами. Типы доставки могут включать бесплатную, стандартную или экспресс-доставку.

    Атрибуты:
        name (CharField): Тип доставки, выбирается из предустановленных вариантов.
        price (DecimalField): Цена выбранного типа доставки.

    Метаданные:
        `name` уникален для каждого типа доставки и индексируется для быстрого поиска.
    """

    FREE_DELIVERY = "FD"
    STANDARD_DELIVERY = "SD"
    EXPRESS_DELIVERY = "ED"

    DELIVERY_PRICE_CHOICES = (
        (FREE_DELIVERY, _("Free delivery")),
        (STANDARD_DELIVERY, _("Standard delivery")),
        (EXPRESS_DELIVERY, _("Express delivery")),
    )
    name = models.CharField(
        max_length=2,
        choices=DELIVERY_PRICE_CHOICES,
        default=FREE_DELIVERY,
        verbose_name=_("Delivery price"),
        db_index=True,
        unique=True,
    )

    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("Price"))

    def __str__(self):
        return str(dict(self.DELIVERY_PRICE_CHOICES).get(self.name))

website/custom_auth/templates/custom_auth/login.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block links %}
    <!--    <title>Megano</title>-->
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
{% endblock %}


{% block body %}
    <body class="Site">
        <!--if lt IE 8
      p.error-browser
          | Ваш браузер&nbsp;
          em устарел!&nbsp;
          a(href="http://browsehappy.com/") Выберите новую версию
              +s
              | браузера здесь&nbsp;
          | для правильного отображения сайта.
      -->
        <main class="Middle">
            <div class="wrapper">
                <div class="header">
                    <h3 class="sign-in">{% trans 'Login' %}</h3>
                </div>
                <div class="clear"></div>

                <form method="post">
                    {% csrf_token %}
                    <div>
                        <input class="user-input" type="text" name="username" id="email" placeholder="E-mail" />
                    </div>
                    <div>

                        <input type="password" name="password" id="pass" placeholder="*********" />
                    </div>
                    <div>
                        <input type="submit" value="Войти" />
                    </div>
                    <a class="forgot-label" href="{% url 'custom_auth:password_reset' %}">{% trans 'Forgot your password' %}?</a>
                    <a class="registr" href="registr.html">
                        {% trans 'Registration' %}
                    </a>
                </form>
            </div>
        </main>

    {% block script %}
            <!--+Middle-->
        <!--    +div.-top-->
        <!--        +breadcrumbs('Главная','Портфолио')-->
        <!--    +Article('portfolio')-->
        <!---->
        <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
        <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
        <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
        <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
        <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
        <script src="{% static 'assets/js/scripts.js' %}"></script>
    {% endblock %}
    </body>

{% endblock %}

website/custom_auth/templates/custom_auth/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'custom_auth:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

website/custom_auth/templates/custom_auth/personal_cabinet.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block links %}
    <!--    <title>Megano</title>-->
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
{% endblock %}

{% block body %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans 'Navigation' %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'custom_auth:personal-cabinet' %}">{% trans 'Personal cabinet' %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url 'custom_auth:profile' %}">{% trans 'Profile' %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url 'custom_auth:profile-orders' %}">{% trans 'Order history' %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url 'custom_auth:viewed-list' %}">{% trans 'Browsing history' %}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Account">
                        <div class="Account-group">
                            <div class="Account-column">
                                <div class="Account-avatar">
                                    {% if profile.photo %}
                                        <img src="{{ profile.photo.url }}" alt="No photo avatar"/>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="Account-column">
                                <div class="Account-name">
                                </div><a class="Account-editLink" href="{% url 'custom_auth:profile' %}">{% trans 'Edit a profile' %}</a>
                            </div>
                        </div>
                        <div class="Account-group">
                            {% if last_order %}
                                <div class="Account-column Account-column_full">
                                    <div class="Order Order_anons">
                                        <div class="Order-personal">
                                            <div class="row">
                                                {% if last_order %}
                                                    <div class="row-block"><a class="Order-title" href="{{ last_order.get_absolute_url }}">{% trans 'Order' %}<span class="Order-numberOrder"> №{{ last_order.pk }} </span>{% trans 'from' %}&#32;<span class="Order-dateOrder">{{ last_order.created_at|date:"d F Y" }}</span></a>
                                                        <div class="Account-editLink"><a href="{% url 'custom_auth:profile-orders' %}">{% trans 'Order history' %}</a>
                                                        </div>
                                                    </div>
                                                    <div class="row-block">

                                                        <div class="Order-info Order-info_delivery">
                                                            <div class="Order-infoType">{% trans 'Type of delivery' %}:
                                                            </div>
                                                            <div class="Order-infoContent">{{ last_order.delivery_price.get_name_display }}
                                                            </div>
                                                        </div>
                                                        <div class="Order-info Order-info_pay">
                                                            <div class="Order-infoType">{% trans 'Payment' %}:
                                                            </div>
                                                            <div class="Order-infoContent">{{ last_order.get_paid_status_display }}
                                                            </div>
                                                        </div>
                                                        <div class="Order-info">
                                                            <div class="Order-infoType">{% trans 'The cost of the order' %}:
                                                            </div>
                                                            <div class="Order-infoContent">{{ last_order.total_price }}
                                                            </div>
                                                        </div>
                                                        <div class="Order-info Order-info_status">
                                                            <div class="Order-infoType">{% trans 'Status' %}:
                                                            </div>
                                                            <div class="Order-infoContent">{{ last_order.get_status_display }}
                                                            </div>
                                                        </div>

                                                    </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <div>
                                    <h2>{% trans "You don't have any orders" %}</h2>
                                </div>
                            {% endif %}
                        </div>
                        <div class="Account-group">
                            {% if viewed_list %}
                                <div class="Account-column Account-column_full">
                                    <div class="Order Order_anons">
                                        <div class="Order-personal">
                                            <div class="row"><h2>{% trans 'Recent views' %}</h2></div>
                                            <div class="row-block">
                                                {% for viewed in viewed_list %}
                                                    <div class="row-block col-mt"><a class="Order-title"
                                                                                     href="{{ viewed.product.get_absolute_url }}"><span
                                                            class="Order-numberOrder">{{ viewed.product.id }}. {{ viewed.product.name }}</span></a>
                                                    </div>
                                                    <div>
                                                        <div class="row-block">
                                                            <div class="Order-info text-ml">
                                                                <div class="Order-infoType">{% trans 'Date of viewing' %}:</div>
                                                                <div class="Order-infoContent"><span
                                                                        class="Order-price">{{ viewed.created_at.date }}</span>
                                                                </div>
                                                            </div>
                                                            <div class="Order-info text-ml">
                                                                <div class="Order-infoType">{% trans 'Viewing time' %}:</div>
                                                                <div class="Order-infoContent"><span
                                                                        class="Order-price">{{ viewed.created_at.time }}</span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                            <div class="row">
                                                <div class="Account-editLink">
                                                    <br>
                                                    <a href="{% url 'custom_auth:viewed-list' %}">{% trans 'Browsing history' %}</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <div>
                                    <h2>{% trans "You don't have any viewed products" %}</h2>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block script %}
        <!--+Middle-->
        <!--    +div.-top-->
        <!--        +breadcrumbs('Главная','Портфолио')-->
        <!--    +Article('portfolio')-->
        <!---->
        <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
        <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
        <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
        <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
        <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
        <script src="{% static 'assets/js/scripts.js' %}"></script>
    {% endblock %}

{% endblock %}