website/cart/urls.py
from django.urls import path

from .views import APICart
from .views import DetailCart

app_name = "cart"

urlpatterns = [
    path("detail/", DetailCart.as_view(), name="detail"),
    path("api/", APICart.as_view(), name="api"),
]

website/catalog/urls.py
from django.urls import path

from . import views
from .views import CatalogListView, catalog_view

app_name = "catalog"

urlpatterns = [
    path("assortment", catalog_view, name="catalog"),
    path("<int:pk>", CatalogListView.as_view(), name="catalog"),
    # products
    path("products/<int:pk>", views.ProductDetailView.as_view(), name="product_detail"),
]

website/discount/urls.py
from django.urls import path

from .views import ActiveDiscountsView
from .views import DiscountCreateView
from .views import DiscountDetailView
from .views import DiscountListView
from .views import DiscountUpdateView

app_name = "discount"

urlpatterns = [
    path("", DiscountListView.as_view(), name="discounts"),
    path("create/", DiscountCreateView.as_view(), name="discount-create"),
    path("detail/<str:slug>/", DiscountDetailView.as_view(), name="discount-detail"),
    path("update/<str:slug>/", DiscountUpdateView.as_view(), name="discount-update"),
    path("active_discounts/", ActiveDiscountsView.as_view(), name="active_discounts"),
]

website/website/urls.py
from itertools import product

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView

# def trigger_error(request):
#     division_by_zero = 1 / 0

urlpatterns = i18n_patterns(
    # Standard URL
    path("", include("core.urls", namespace="default")),
    path("admin/", admin.site.urls),
    path("account/", include("custom_auth.urls")),
    path("order/", include("order.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("discount/", include("discount.urls")),
    path("payment/", include("payment.urls")),
    # API
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/v1/", include("review.urls")),
    # path('sentry-debug/', trigger_error),
) + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

website/discount/forms.py
from catalog.models import Category
from catalog.models import Product
from django import forms
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from .models import Discount
from .models import ProductGroup


class DiscountCreationForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _('The name of the discount, for example, "Sale 11.11."'),
            },
        ),
        error_messages={
            "max_length": _("Only 100 characters are allowed"),
        },
        label=_("Name of the discount"),
    )
    kind = forms.ChoiceField(
        required=True,
        choices=Discount.KIND_CHOICES,
        widget=forms.Select(
            attrs={"class": "form-select"},
        ),
        error_messages={
            "required": _("Fill in the required field"),
        },
        label=_("Type discount"),
    )
    method = forms.ChoiceField(
        required=True,
        choices=Discount.METHOD_CHOICES,
        widget=forms.Select(
            attrs={"class": "form-select"},
        ),
        error_messages={
            "required": _("Fill in the required field"),
        },
        label=_("Discount method"),
    )
    quantity_gt = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Maximum quantity"),
            },
        ),
        label=_("Maximum quantity"),
    )
    quantity_lt = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(
            attrs={"class": "form-control", "placeholder": _("Minimum quantity")},
        ),
        label=_("Minimum quantity"),
    )
    value = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={"class": "form-control", "placeholder": _("Enter the discount value")},
        ),
        label=_("Discount value"),
    )
    description = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": _("Description of the discount..."), "rows": 3},
        ),
        label=_("Description"),
    )
    start_date = forms.DateField(
        widget=forms.DateInput(
            attrs={"class": "form-control", "type": "date"},
        ),
        label=_("Discount start date"),
    )
    end_date = forms.DateField(
        widget=forms.DateInput(
            attrs={"class": "form-control", "type": "date"},
        ),
        label=_("Discount end date"),
    )
    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={"class": "form-check-input"},
        ),
        label=_("Active"),
    )
    archived = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={"class": "form-check-input"},
        ),
        label=_("Archived"),
    )
    products = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "form-check-input"},
        ),
        label=_("Select the products to apply the discount to"),
    )
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "form-check-input"},
        ),
        label=_("Select the product categories in which to apply the discount"),
    )
    products_group = forms.ModelMultipleChoiceField(
        queryset=ProductGroup.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "form-check-input"},
        ),
        label=_("Select the product group to which the discount applies"),
    )

    class Meta:
        model = Discount
        fields = [
            "name",
            "kind",
            "method",
            "quantity_gt",
            "quantity_lt",
            "value",
            "description",
            "start_date",
            "end_date",
            "is_active",
            "archived",
            "products",
            "categories",
            "product_groups",
        ]

    def __init__(self, *args, **kwargs):
        """
        Устанавливаем атрибут value к полям start_date и end_date со значением
        текущей даты
        """
        super().__init__(*args, **kwargs)
        self.fields["end_date"].widget.attrs["value"] = now().date()
        self.fields["start_date"].widget.attrs["value"] = now().date()

    def clean_end_date(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        if start_date and end_date and end_date < start_date:
            raise forms.ValidationError(_("The discount expiration date cannot be earlier than the start date."))

        return end_date

website/discount/views.py
import logging

from cart.cart import Cart
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import DiscountCreationForm
from .models import Discount


class DiscountListView(UserPassesTestMixin, ListView):
    """
    Представление для отображения всех скидок:
    Доступно только аутентифицированному пользователя, у которого есть права админа.
    """

    model = Discount
    template_name = "discount/discount_list.html"
    context_object_name = "discounts"

    def test_func(self) -> bool:
        """
        Метод test_func, чтобы не пропускать запросы
        не аутентифицированного пользователя без прав администратора
        """
        if not self.request.user.is_staff:
            return False

        return True


class DiscountDetailView(UserPassesTestMixin, DetailView):
    """
    Представление для отображения формы деталей скидки:
    Доступно только аутентифицированному пользователя, у которого есть права админа.
    """

    model = Discount
    context_object_name = "discount"
    template_name = "discount/discount_detail.html"

    def test_func(self) -> bool:
        """
        Метод test_func, чтобы не пропускать запросы
        не аутентифицированного пользователя без прав администратора
        """
        if not self.request.user.is_staff:
            return False

        return True

    def __get_description_type_discount(self):
        """Возвращает описание типа скидки"""
        if self.object.kind == "PT":
            return _("product discount")
        elif self.object.kind == "ST":
            return _("discount on a set of products")
        elif self.object.kind == "CT":
            cart = Cart(self.request)
            return _("discount on the shopping cart")

    def __get_description_method_discount(self):
        """Возвращает описание метода расчета скидки"""
        if self.object.method == "PT":
            return _("percentage discount")
        elif self.object.method == "SM":
            cost_discount = self.object.total_cost_l
            return _("the discount is valid from a certain cost {cost_discount}")
        elif self.object.method == "FD":
            return _("fixed discount amount")

    def __get_priority_discount(self):
        """Возвращает приоритетность скидки"""
        if self.object.priority == 1:
            return _("the lowest")
        elif self.object.priority == 2:
            return _("low")
        elif self.object.priority == 3:
            return _("middle")
        elif self.object.priority == 4:
            return _("high")
        elif self.object.priority == 5:
            return _("the highest")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        description_type = self.__get_description_type_discount()
        description_method = self.__get_description_method_discount()
        description_priority = self.__get_priority_discount()

        if self.object.kind == "PT":
            context["products"] = self.object.products
        elif self.object.kind == "ST":
            context["product_groups"] = self.object.product_groups
        elif self.object.kind == "CT":
            quantity_l = self.object.quantity_l
            quantity_g = self.object.quantity_g
            total_cost_l = self.object.total_cost_l
            context["cart_products"] = {
                "quantity_l": quantity_l,
                "quantity_g": quantity_g,
                "total_cost_l": total_cost_l,
            }

        if self.object.method == "PT":
            context["percent"] = self.object.percent
        elif self.object.method == "SM":
            context["sum_discount"] = self.object.price
        elif self.object.method == "FD":
            context["fixed_price"] = self.object.price

        context["description_type"] = description_type
        context["description_method"] = description_method
        context["description_priority"] = description_priority
        context["description"] = self.object.description
        context["start_date"] = self.object.start_date
        context["end_date"] = self.object.end_date
        context["is_active"] = self.object.is_active
        context["archived"] = self.object.archived
        return context


class DiscountCreateView(UserPassesTestMixin, CreateView):
    """
    Представление для отображения формы создания скидок:
        - скидка на товары
        - скидка на корзину
        - скидка на группу товаров

    Доступно только аутентифицированному пользователя, у которого есть права админа.
    """

    template_name = "discount/discount_create.html"
    form_class = DiscountCreationForm

    def test_func(self) -> bool:
        """
        Метод test_func, чтобы не пропускать запросы
        не аутентифицированного пользователя без прав администратора
        """
        if not self.request.user.is_staff:
            return False

        return True

    def form_valid(self, form):
        """
        Если форма валидна, сохраняем объект и выполняем перенаправление.
        """
        with transaction.atomic():
            self.object = form.save()

        return super().form_valid(form)


class DiscountUpdateView(UserPassesTestMixin, UpdateView):
    """
    Представление для обновления записи скидки

    Атрибуты:
        template_name - шаблон для отображения формы обновления скидки
        model - модель, которую обновляем
        form_class - форма для обновления записи о скидке
        success_url - путь для перенаправления после успешного обновления

    Применяем UserPassesTestMixin для того, чтобы только админ
    мог обновлять запись о скидке
    """

    template_name = "discount/discount_update.html"
    model = Discount
    form_class = DiscountCreationForm
    success_url = reverse_lazy("discount:discount-list")

    def get_object(self, queryset=None):
        """
        Получаем запись модели Discount из базы данных по полю slug
        """
        queryset = get_object_or_404(Discount, slug=self.kwargs["slug"])
        return queryset

    def test_func(self):
        """
        Метод test_func, чтобы не пропускать запросы
        не аутентифицированного пользователя без прав администратора
        """
        return self.request.user.is_staff

    def get_success_url(self):
        """
        Определяем путь для перенаправления после успешного обновления записи.
        """
        return reverse_lazy(
            "discount:discount-update",
            kwargs={"slug": self.object.slug},
        )


logger = logging.getLogger(__name__)


class ActiveDiscountsView(ListView):
    """
    Представление для  получения и отображения списка активных скидок.
    Активные скидки определяются как те, которые имеют значение active=True
    и находятся в пределах заданного временного интервала (между start_date и
    end_date, если они указаны)
    """

    model = Discount
    template_name = "discount/active_discounts.html"
    context_object_name = "discounts"

    def get_queryset(self):
        """Получает QuerySet активных скидок.
        Метод фильтрует скидки по следующим критериям:
        - Скидка должна быть активной (active=True).
        - Дата начала скидки должна быть либо не указана, либо меньше или равна текущей дате.
        - Дата окончания скидки должна быть либо не указана, либо больше или равна текущей дате."""
        try:
            return (
                Discount.objects.filter(active=True)
                .filter(Q(start_date__isnull=True) | Q(start_date__lte=timezone.now()))
                .filter(Q(end_date__isnull=True) | Q(end_date__gte=timezone.now()))
            )
        except Exception as e:
            logger.error("Ошибка при получении скидок: %s", e, exc_info=True)
            return Discount.objects.none()

website/discount/templates/discount/active_discounts.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block description %}
    <meta name="description" content="Описание страницы">
{% endblock %}

{% block links %}
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
{% endblock %}

{% block title %}
    Активные Скидки
{% endblock %}

{% block body %}
    <ul>
        {% for discount in discounts %}
            <li>
                <h2>{{ discount.title }}</h2>
                <p>{{ discount.description }}</p>
                {% if discount.start_date or discount.end_date %}
                    <div>
                        {% if discount.start_date %}
                            <span>{% trans 'Start' %}: {{ discount.start_date|date:"Y-m-d H:i" }}</span>
                        {% endif %}
                        {% if discount.end_date %}
                            <span>{% trans 'End' %}: {{ discount.end_date|date:"Y-m-d H:i" }}</span>
                        {% endif %}
                    </div>
                {% endif %}
            </li>
        {% empty %}
            <li>{% trans 'There are no active discounts' %}.</li>
        {% endfor %}
    </ul>
{% endblock %}

{% block script %}
    <script src="assets/plg/jQuery/jquery-3.5.0.slim.min.js"></script>
    <script src="assets/plg/form/jquery.form.js"></script>
    <script src="assets/plg/form/jquery.maskedinput.min.js"></script>
    <script src="assets/plg/range/ion.rangeSlider.min.js"></script>
    <script src="assets/plg/Slider/slick.min.js"></script>
    <script src="assets/js/scripts.js"></script>
{% endblock %}

website/discount/templates/discount/discount_create.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block links %}
    <!--    <title>Megano</title>-->
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
{% endblock %}

{% block body %}
  <div class="wrap-container">
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group">
          <label class="text-form">{{ field.label }}</label>
          {{ field }}
          {% if field.errors %}
            {% for error in field.errors %}
              <div class="highlight-field text-form">{{ error }}</div>
            {% endfor %}
          {% endif %}
        </div>
      {% endfor %}
      <button type="submit" class="button-discount-form">Создать скидку</button>
    </form>
  </div>


  {% block script %}
        <!--+Middle-->
    <!--    +div.-top-->
    <!--        +breadcrumbs('Главная','Портфолио')-->
    <!--    +Article('portfolio')-->
    <!---->
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
  {% endblock %}

{% endblock %}

website/discount/templates/discount/discount_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block links %}
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
{% endblock %}

{% block body %}
  <div class="wrap-container">
    <h2>{{ discount.name }}</h2>
    <div class="Discount-description">
      <div class="wrap-discount-description">
        <span>{% trans 'Type discount' %}: {{ description_type }}</span>
        {% if products %}
          {% for product in products.all %}
            <span>{{ product.name }}</span>
            {% for price in product.prices.all %}
                <a href="{{ price.product.get_absolute_url }}">{{ price.price }}</a>
            {% endfor %}
          {% endfor %}
        {% elif product_groups %}
          <span>{% trans 'Name group products' %}: {{ product_groups.name }}</span>
          <span>{% trans 'Description group products' %}: {{ product_groups.description }}</span>
          <span>{% trans 'Archived status' %}: {{ product_groups.archived }}</span>
          {% for product in product_groups %}
            <span>{{ product.name }}</span>
            {% for price in product.prices.all %}
                <a href="{{ price.product.get_absolute_url }}">{{ price.price }}</a>
            {% endfor %}
          {% endfor %}
        {% elif cart_products %}
          <span>{% trans 'Min quantity products in cart' %}: {{ cart_products.quantity_l }}</span>
          <span>{% trans 'Max quantity products in cart' %}: {{ cart_products.quantity_g }}</span>
          <span>{% trans 'Total cost products in cart' %}: {{ cart_products.total_cost_l }}</span>
        {% endif %}

        <span>{% trans 'Discount calculation method' %}: {{ description_method }}</span>
        {% if percent %}
          <span>{% trans 'Percent discount' %}: {{ percent }}%</span>
        {% elif sum_discount %}
          <span>{% trans 'The discount is valid for the amount of' %}: {{ sum_discount }}$</span>
        {% elif fixed_price %}
          <span>{% trans 'The discount has a fixed price' %}: {{ fixed_price }}$</span>
        {% endif %}

        <span>{% trans 'Discount priority' %}: {{ description_priority }}</span>
      </div>
    </div>
    <a href="{% url 'discount:discounts' %}">{% trans 'Back to discounts' %}</a>
  </div>


  {% block script %}
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
  {% endblock %}

{% endblock %}

website/discount/templates/discount/discount_email.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <style>
        .body {
            font-family: Arial,sans-serif;
            margin: 0; padding: 0;
            background-color: #f7f7f7;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: #ffffff;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 8px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 24px;
            color: #333;
        }
        .product-name {
            font-size: 18px;
            font-weight: bold;
            color: #333;
            margin-bottom: 5px;
            cursor: pointer;
        }
        .span-price {
            font-size: 20px;
            color: #ed5c16
        }
        .footer {
            padding: 20px;
            background: #f1f3f5;
            text-align: center;
            font-size: 14px;
            color: #888888;
        }
        .footer a {
            color: #4caf50;
            text-decoration: none;
        }
        .footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body class="body">
    <div class="container">
        <div class="header">
            <h1>Сегодняшние скидки</h1>
        </div>

        <p style="font-size: 20px; color: #555;">
            {{ username }}, привет! Заходи к нам, сегодня есть много интересных предложений, вот лишь малая часть из них:
        </p>

        {% for product in products %}
            <div style="display: flex; align-items: center; margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 15px;">
                <div style="flex: 1; text-align: center;">
                    <img src="cid:image_{{ forloop.counter }}" alt="Image №{{ forloop.counter }}" style="max-width: 100px; border-radius: 4px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                </div>
                <div style="flex: 2; margin-left: 15px;">
                    <a href="{{ protocol }}{{ domain }}{% url 'catalog:product_detail' pk=product.pk %}" class="product-name">
                        {{ product.name }}
                    </a>
                    <div style="font-size: 16px; color: #888;">
                        Цена: <span class="span-price">{{ product.price }} ₽</span>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="footer">
            &copy; {{ year }} Megano. Все права защищены. <br>
            <a href="{{ protocol }}{{ domain }}">Посетить сайт</a> | <a href="mailto:{{ email }}">Связаться с
            поддержкой</a>
        </div>

    </div>
</body>
</html>

website/discount/templates/discount/discount_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block links %}
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
{% endblock %}

{% block body %}
  <div class="wrap-container">
    <div>
      {% for discount in discounts %}
        <div class="Discount-description">
          <a href="{{ discount.get_absolute_url }}">{{ discount.name }}</a>
          <span>{{ discount.description }}</span>
        </div>
      {% endfor %}
    </div>
  </div>


  {% block script %}
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
  {% endblock %}

{% endblock %}