website/cart/urls.py
from django.urls import path

from .views import APICart
from .views import DetailCart

app_name = "cart"

urlpatterns = [
    path("detail/", DetailCart.as_view(), name="detail"),
    path("api/", APICart.as_view(), name="api"),
]

website/catalog/urls.py
from django.urls import path

from . import views
from .views import CatalogListView, catalog_view

app_name = "catalog"

urlpatterns = [
    path("assortment", catalog_view, name="catalog"),
    path("<int:pk>", CatalogListView.as_view(), name="catalog"),
    # products
    path("products/<int:pk>", views.ProductDetailView.as_view(), name="product_detail"),
]

website/comparison/urls.py
from django.urls import path

from . import views

app_name = "comparison"

urlpatterns = [
    path("", views.ComparisonView.as_view(), name="comparison_page"),
    path("add/", views.ComparisonAddApiView.as_view(), name="comparison_add"),
    path("delete/", views.ComparisonDeleteApiView.as_view(), name="comparison_delete"),
]

website/website/urls.py
from itertools import product

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView

# def trigger_error(request):
#     division_by_zero = 1 / 0

urlpatterns = i18n_patterns(
    # Standard URL
    path("", include("core.urls", namespace="default")),
    path("admin/", admin.site.urls),
    path("account/", include("custom_auth.urls")),
    path("order/", include("order.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("discount/", include("discount.urls")),
    path("payment/", include("payment.urls")),
    # API
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/v1/", include("review.urls")),
    # path('sentry-debug/', trigger_error),
) + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

website/catalog/forms.py
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text"]

    def clean_text(self):
        text = self.cleaned_data.get("text")
        if not text:
            raise forms.ValidationError("Отзыв не может быть пустым.")
        return text

website/catalog/views.py
import json
from collections import defaultdict
from itertools import product

from django.core.cache import cache
from django.db import transaction
from django.db.models import (
    Count,
    Max,
    Sum,
)
from django.db.models import Min, Q
from django.db.models import OuterRef
from django.db.models import Prefetch
from django.db.models import Subquery
from django.db.models.functions import Round
from django.http import HttpRequest
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import ListView
from drf_spectacular.utils import extend_schema
from rest_framework import permissions
from rest_framework import status
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from website.settings import PRODUCTS_KEY

from .models import Price
from .models import Product
from .models import ProductImage
from .models import Seller
from .models import Specification
from .models import Tag
from .models import Viewed
from .serializers import ViewedSerializer
from .models import ViewedSession
from .utils import generate_sort_param, sort_convert


def catalog_view(request: HttpRequest):
    return render(request, "catalog/catalog.html")


class CatalogListView(ListView):
    """
    Представление для отображения списка продуктов в каталоге.

    Это представление обрабатывает запросы на отображение продуктов в
    определенной категории, предоставляет возможность фильтрации по
    различным параметрам, таким как продавцы, производители,
    ограниченные серии, диапазон цен, название, спецификации и теги.

    Атрибуты:
        template_name (str): Путь к шаблону, который будет использоваться для отображения.
        model (Model): Модель, используемая для получения данных (Product).
        context_object_name (str): Имя контекста, под которым будут доступны продукты в шаблоне.

    """

    template_name = "catalog/catalog.html"
    model = Product
    context_object_name = "products"
    paginate_by = 12

    def get_context_data(self, **kwargs):
        """
            Получаем контекст для шаблона.

            Объединяет контекст, предоставляемый родительским классом, с дополнительными
            параметрами, полученными из метода get_param.

            Параметры:
                **kwargs: Дополнительные именованные аргументы.

            Возвращает:
                dict: Объединенный контекст для шаблона.
        """
        context = super().get_context_data(**kwargs)
        context.update(self.get_param())
        return context

    def sort_queryset(self, queryset, sort):
        """
            Сортирует набор данных по заданному параметру.

            Обновляет параметры сортировки в сессии и сортирует переданный
            queryset в соответствии с указанным параметром.

            Параметры:
                queryset (QuerySet): Набор данных, который необходимо отсортировать.
                sort (str): Параметр сортировки.

            Возвращает:
                QuerySet: Отсортированный набор данных.
        """
        sort_convert(self.request.session, sort)
        return queryset.order_by(sort)

    def get_last_sort(self, session):
        """
            Получает последний использованный параметр сортировки из сессии.

            Параметры:
                session (dict): Словарь сессии, содержащий параметры сортировки.

            Возвращает:
                str: Параметр последней сортировки или None, если сортировка не была установлена.
        """
        sorting = json.loads(session["sort_catalog"])
        for key, value in sorting.items():
            if value["style"]:
                return value["param"]

    def get_param(self):
        """
            Получаем дополнительные параметры для контекста.

            Собирает информацию о продуктах, продавцах, производителях, спецификациях и тегах
            для текущей категории и возвращает это в виде словаря.

            Возвращает:
                dict: Словарь с дополнительными параметрами для контекста.
        """

        category_id = self.kwargs.get("pk")

        products_with_related = Product.objects.prefetch_related("specifications").filter(category__id=category_id)

        sellers = Seller.objects.all()
        manufactures = products_with_related.values_list("manufacture", flat=True).distinct()

        # Получаем все спецификации для всех продуктов в категории
        specifications = (
            Specification.objects.filter(product__in=products_with_related).distinct()
        )

        # Группируем спецификации по имени
        grouped_specifications = defaultdict(set)
        for spec in specifications:
            grouped_specifications[spec.name.name].add(spec.value)

        # Получить уникальные теги
        tags = Tag.objects.filter(products__isnull=False).distinct()

        if "sort_catalog" not in self.request.session:
            self.request.session["sort_catalog"] = generate_sort_param()
        sorting = json.loads(self.request.session["sort_catalog"])

        return {
            "sellers": sellers,
            "manufactures": manufactures,
            "grouped_specifications": grouped_specifications.items(),
            "tags": tags,
            "sort": sorting,
            "category_id": category_id,
        }

    def get_queryset(self):
        """
            Получаем список продуктов с учетом кэширования.

            Извлекает список продуктов для текущей категории, используя кэш для
            повышения производительности. Если кэш пуст, выполняет запрос к базе данных.

            Возвращает:
                QuerySet: Набор данных с продуктами для текущей категории.
        """
        category_id = self.kwargs.get("pk")
        cache_key = PRODUCTS_KEY.format(category_id=category_id)
        queryset = cache.get(cache_key)
        price_subquery = Price.objects.filter(product=OuterRef("pk")).values("pk")
        if not queryset:
            queryset = (
                Product.objects.filter(category__id=category_id, archived=False)
                .select_related("category")
                .annotate(
                    price=Round(Min("prices__price"), precision=2),
                    price_pk=Subquery(price_subquery),
                    quantity=Sum("prices__sold_quantity"),
                    date=Max("prices__created_at"),
                    rating=Count("review__created_at"),
                )
            )

        cache.set(cache_key, queryset, timeout=60)

        sort = self.request.GET.get("sort")
        if sort:
            sort_convert(self.request.session, sort)
            queryset = self.sort_queryset(queryset, sort)
        return queryset

    def filter_products(self, products, request):
        """
            Фильтруем продукты по выбранным параметрам.

            Этот метод применяет фильтры к переданному набору продуктов на основе
            выбранных пользователем параметров, таких как продавцы, производители,
            диапазон цен, название, спецификации и теги.

            Параметры:
                products (QuerySet): Набор данных с продуктами, к которому будут применены фильтры.
                request (HttpRequest): Объект запроса, содержащий параметры фильтрации.

            Возвращает:
                QuerySet: Отфильтрованный набор данных с продуктами.
        """
        selected_sellers = request.POST.getlist("seller[]")
        selected_manufactures = request.POST.getlist("manufacture[]")
        selected_limited_edition = request.POST.get("limited_edition")
        selected_range_price = request.POST.get("price")
        selected_title = request.POST.get("title")
        selected_specifications = request.POST.getlist("specification")
        selected_tags = request.POST.getlist("tags")


        # Фильтрация по диапазону цен
        if selected_range_price:
            try:
                price_min, price_max = map(float, selected_range_price.split(";"))
                products = products.filter(price__range=[price_min, price_max])
            except ValueError:
                pass  # Игнорируем ошибку, если значения некорректные

        # Фильтрация по названию
        if selected_title:
            products = products.filter(name__icontains=selected_title)

        # Фильтрация по продавцам
        if selected_sellers:
            products = products.filter(prices__seller__id__in=selected_sellers)

        # Фильтрация по производителям
        if selected_manufactures:
            products = products.filter(manufacture__in=selected_manufactures)

        # Фильтрация по ограниченным сериям
        if selected_limited_edition:
            products = products.filter(limited_edition=True)

        # Фильтрация по характеристикам
        if selected_specifications:
            products = products.filter(specifications__value__in=selected_specifications).distinct()

        # Фильтрация по тегам
        if selected_tags:
            products = products.filter(tags__id__in=selected_tags).distinct()

        last_sort = self.get_last_sort(self.request.session)
        # Сортировка
        if last_sort:
            products = products.order_by(last_sort)

        return products

    def clear_cache(self, category_id):
        """
            Метод для очистки кэша по категории.

            Этот метод удаляет кэшированные данные для заданной категории, что
            позволяет обновить информацию о продуктах.

            Параметры:
                category_id (int): Идентификатор категории, для которой нужно очистить кэш.

            Возвращает:
                None
        """
        cache_key = PRODUCTS_KEY.format(category_id=category_id)
        cache.delete(cache_key)  # Очистка кэша по ключу

    def post(self, request, *args, **kwargs):
        """
            Обработка POST-запроса для фильтрации продуктов.

website/catalog/templates/catalog/catalog.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block description %}
    <meta name="description" content="Описание страницы">
{% endblock %}

{% block links %}
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
{% endblock %}

{% block title %}
    {% translate 'Catalog' %}
{% endblock %}

{% block body %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% translate 'Filter' %}</strong>
                        </header>
                        <div class="Section-columnContent">
                            <form class="form" action="#" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <div class="range Section-columnRange">
                                        <input class="range-line" id="price" name="price" type="text" data-type="double" data-min="1" data-max="500000" data-from="7" data-to="50000" />
                                        <div class="range-price">{% translate 'Price' %}:&#32;
                                            <div class="rangePrice">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input class="form-input form-input_full" id="title"
                                           name="title" type="text"
                                           placeholder="{% trans 'Title' %}"/>
                                </div>
                                <div class="form-group">
                                    <strong class="Section-title">{% trans 'Seller' %}</strong>
                                    <select id="seller" name="seller[]" multiple>
                                        {% for seller in sellers %}
                                            <option value="{{ seller.id }}">
                                                {{ seller.name }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="form-group">
                                    <strong class="Section-title">{% trans 'Manufacture' %}:</strong>
                                    <select id="manufacture" name="manufacture[]" multiple>
                                        {% for manufacture in manufactures %}
                                            <option value="{{ manufacture }}">
                                                {{ manufacture }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="toggle">
                                        <input type="checkbox" name="limited_edition">
                                        <span class="toggle-box"></span>
                                        <span class="toggle-text">{% trans 'Limited series only' %}</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <strong class="Section-title">{% trans 'Specifications' %}</strong>
                                    {% for name, values in grouped_specifications %}
                                        <label class="toggle">
                                            <span class="toggle-text">{{ name }}</span>
                                        </label>
                                        <div>
                                            {% for value in values %}
                                                <label class="toggle">
                                                    <input type="checkbox" name="specification" value="{{ value }}">
                                                    <span class="toggle-box"></span>
                                                    <span class="toggle-text">{{ value }}</span>
                                                </label>
                                            {% endfor %}
                                            <br><br>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="form-group">
                                    <div class="buttons">
                                        <button type="submit" class="btn btn_square btn_dark btn_narrow">{% trans 'Filter' %}</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans 'Popular tags' %}</strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="buttons">
                                {% for tag in tags %}
                                    <a class="btn btn_default btn_sm" href="#">{{ tag.name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Sort">
                        <div class="Sort-title">{% trans 'Sort by' %}:
                        </div>
                        <div class="Sort-variants">
                            <a class="Sort-sortBy {{ sort.quantity.style }}" href="{% url 'catalog:catalog' category_id %}?sort={{ sort.quantity.param }}">{% trans 'Popularity' %}</a>
                            <a class="Sort-sortBy {{ sort.price.style }}" href="{% url 'catalog:catalog' category_id %}?sort={{ sort.price.param }}">{% trans 'Price' %}</a>
                            <a class="Sort-sortBy {{ sort.rating.style }}" href="{% url 'catalog:catalog' category_id %}?sort={{ sort.rating.param }}">{% trans 'Reviews' %}</a>
                            <a class="Sort-sortBy {{ sort.date.style }}" href="{% url 'catalog:catalog' category_id %}?sort={{ sort.date.param }}">{% trans 'Novelty' %}</a>
                        </div>
                    </div>
                    <div class="Cards">
                        {% csrf_token %}
                        {% for product in products %}
                            <div class="Card" {% if forloop.counter > 4 %} hide_md {% endif %}
                                             {% if forloop.counter > 6 %} hide_1450 {% endif %}>
                                <a class="Card-picture" href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.preview.url }}" alt=""/>
                                </a>
                                <div class="Card-content">
                                    <strong class="Card-title">
                                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                    </strong>
                                    <div class="Card-description">
                                        <div class="Card-cost">
                                            <span class="Card-price">{{ product.price|floatformat:2 }}$ </span>
                                        </div>
                                        <div class="Card-category">{{ product.category }}
                                        </div>
                                        <div class="Card-hover">
                                            <form method="post" action="{% url 'comparison:comparison_add'%}">
                                                {% csrf_token %}
                                                <input type="hidden" name="product_id" value="{{product.pk}}">
                                                <button class="Card-btn-comp" type="submit"></button>
                                            </form>
                                            <a class="Card-btn" data-product_id="{{ product.pk }}" data-price_id="{{ product.price_pk }}">
                                                <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>

                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                     <div class="Pagination">
                            <div class="Pagination-ins">
                                {% if is_paginated %}
                                    {% if page_obj.has_previous %}
                                        <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.previous_page_number }}">
                                            <img src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/>
                                        </a>
                                    {% endif %}
                                    {% for num in page_obj.paginator.page_range %}
                                        {% if page_obj.number == num %}
                                            <a class="Pagination-element Pagination-element_current" href="#">
                                                <span class="Pagination-text">{{ num }}</span>
                                            </a>
                                        {% else %}
                                            <a class="Pagination-element" href="?page={{ num }}">
                                                <span class="Pagination-text">{{ num }}</span>
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <a class="Pagination-element Pagination-element_next" href="?page={{ page_obj.next_page_number }}">
                                            <img src="{% static 'assets/img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/>
                                        </a>
                                    {% endif %}
                                {% endif %}
                            </div>
                     </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

<!--    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>-->
<!--    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/scripts.js' %}"></script>-->
    <script src="{% static 'assets/js/cart/collect_data_cart.js' %}"></script>
    <script src="{% static 'assets/js/cart/add_product_cart.js' %}"></script>
{% endblock %}