website/cart/urls.py
from django.urls import path

from .views import APICart
from .views import DetailCart

app_name = "cart"

urlpatterns = [
    path("detail/", DetailCart.as_view(), name="detail"),
    path("api/", APICart.as_view(), name="api"),
]

website/catalog/urls.py
from django.urls import path

from . import views
from .views import CatalogListView, catalog_view

app_name = "catalog"

urlpatterns = [
    path("assortment", catalog_view, name="catalog"),
    path("<int:pk>", CatalogListView.as_view(), name="catalog"),
    # products
    path("products/<int:pk>", views.ProductDetailView.as_view(), name="product_detail"),
]

website/comparison/urls.py
from django.urls import path

from . import views

app_name = "comparison"

urlpatterns = [
    path("", views.ComparisonView.as_view(), name="comparison_page"),
    path("add/", views.ComparisonAddApiView.as_view(), name="comparison_add"),
    path("delete/", views.ComparisonDeleteApiView.as_view(), name="comparison_delete"),
]

website/core/urls.py
from core.imports.views import import_products_view
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("import/", import_products_view, name="import_view"),
]

website/custom_auth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from .views import LogInView
from .views import LogOutView
from .views import PersonalCabinet
from .views import ProfileOrdersView
from .views import ProfileView
from .views import RegisterView
from .views import ResetCashView
from .views import SettingsChangeView
from .views import SettingsPageView
from .views import UserPasswordResetConfirmView
from .views import ViewedListView

app_name = "custom_auth"

urlpatterns = [
    path("login/", LogInView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("settings/", SettingsPageView.as_view(), name="settings"),
    path("settings/change/", SettingsChangeView.as_view(), name="settings_change"),
    path("cashing/", ResetCashView.as_view(), name="cashing"),
    path("viewed/", ViewedListView.as_view(), name="viewed-list"),
    path("personal_cabinet/", PersonalCabinet.as_view(), name="personal-cabinet"),
    path("profile_orders/", ProfileOrdersView.as_view(), name="profile-orders"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="custom_auth/password_reset.html",
            email_template_name="account/password_reset_email.html",
            success_url=reverse_lazy("account:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="custom_auth/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(template_name="custom_auth/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

website/discount/urls.py
from django.urls import path

from .views import ActiveDiscountsView
from .views import DiscountCreateView
from .views import DiscountDetailView
from .views import DiscountListView
from .views import DiscountUpdateView

app_name = "discount"

urlpatterns = [
    path("", DiscountListView.as_view(), name="discounts"),
    path("create/", DiscountCreateView.as_view(), name="discount-create"),
    path("detail/<str:slug>/", DiscountDetailView.as_view(), name="discount-detail"),
    path("update/<str:slug>/", DiscountUpdateView.as_view(), name="discount-update"),
    path("active_discounts/", ActiveDiscountsView.as_view(), name="active_discounts"),
]

website/website/urls.py
from itertools import product

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView

# def trigger_error(request):
#     division_by_zero = 1 / 0

urlpatterns = i18n_patterns(
    # Standard URL
    path("", include("core.urls", namespace="default")),
    path("admin/", admin.site.urls),
    path("account/", include("custom_auth.urls")),
    path("order/", include("order.urls")),
    path("catalog/", include("catalog.urls")),
    path("cart/", include("cart.urls")),
    path("comparison/", include("comparison.urls")),
    path("discount/", include("discount.urls")),
    path("payment/", include("payment.urls")),
    # API
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/v1/", include("review.urls")),
    # path('sentry-debug/', trigger_error),
) + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

website/comparison/models.py
from catalog.models import Product
from django.db import models
from django.utils.translation import gettext_lazy as _

from website import settings


class Comparison(models.Model):
    """
    Модель для хранения товаров, добавленных в список сравнения пользователем.

    Этот класс представляет связь между пользователем и товаром в контексте
    функции сравнения товаров. Каждый пользователь может добавлять товары
    в список сравнения, и каждая пара "пользователь-товар" должна быть уникальной.

    Атрибуты:
        user (ForeignKey): Ссылка на модель пользователя, которая добавила товар в сравнение.
        product (ForeignKey): Ссылка на модель товара, добавленного в сравнение.

    Метаданные:
        unique_together (tuple): Ограничение, гарантирующее уникальность каждой комбинации
        пользователя и товара в списке сравнения.
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_("User"), db_index=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_("Comparison product"), db_index=True)

    class Meta:
        unique_together = ("user", "product")

website/core/models.py
from catalog.models import Product
from django.db import models
from django.utils.translation import gettext_lazy as _


class Banner(models.Model):
    """
    Модель Banner представляет собой рекламный баннер, связанный с определённым продуктом.

    Поля:
    - product: Внешний ключ, указывающий на связанный продукт.
    - deadline_data: Дата, до которой баннер активен.
    - created_date: Дата создания баннера.
    - active: Логическое значение, показывающее, активен ли баннер.

    Связь:
    Один баннер может быть связан с одним продуктом, но продукт может иметь множество баннеров.
    """

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="banner",
        verbose_name=_("Product"),
    )
    text = models.TextField(max_length=200, verbose_name=_("Text banner"), default="", null=True, blank=True)
    deadline_data = models.DateField(verbose_name=_("Deadline Date"))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Created_date"))
    active = models.BooleanField(verbose_name=_("Active"), default=True)

website/catalog/forms.py
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text"]

    def clean_text(self):
        text = self.cleaned_data.get("text")
        if not text:
            raise forms.ValidationError("Отзыв не может быть пустым.")
        return text

website/cart/views.py
from django.views.generic import TemplateView
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK
from rest_framework.status import HTTP_201_CREATED
from rest_framework.status import HTTP_204_NO_CONTENT
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny

from .cart import Cart


class DetailCart(TemplateView):
    """
    Представление для отображения страницы корзины
    """

    template_name = "cart/cart_detail.html"

    def get_context_data(self, **kwargs) -> dict:
        """
        Возвращает контекст в шаблон
        """
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        context["info_cart"] = cart.get_context_info()
        context["total_quantity_products"] = cart.total_quantity
        return context


class APICart(APIView):
    """
    API для взаимодействия с корзиной
    """
    permission_classes = [AllowAny]

    def get(self, request: Request) -> Response:
        """
        Возвращает информацию о товарах в корзине
        Формат корзины:
        {
            "product1": {
                    "quantity": "кол-во товара (int)",
                    "product_id": "id товара (int)",
                    "price": "цена товара (float)",
                    "seller_id": "id продавца (int)",
                    "seller_name": "имя продавца (str)",
                    "to_order": "в заказе товара или нет (bool)",
                    "cost_product": "стоимость товара (str),"
            },
            "total_quantity": "общее кол-во товара в корзине (int)",
            "total_cost": "общая стоимость товаров в корзине (str)",
        }
        """
        cart = Cart(request)
        return Response(cart.cart)

    def post(self, request: Request) -> Response:
        """
        Добавляет товар в корзину
        """
        cart = Cart(request)
        data = request.data
        product_id = data["product_id"]
        price_id = data["price_id"]
        quantity = 1
        if "quantity" in data:
            quantity = data["quantity"]
        cart.add(product_id, price_id, quantity)
        return Response(status=HTTP_201_CREATED)

    def patch(self, request: Request) -> Response:
        """
        Обновляет кол-во товаров в корзине
        """
        cart = Cart(request)
        data = request.data
        product_id = data["product_id"]
        quantity = data["quantity"]
        seller_id = data["seller_id"]
        cart.update_product(product_id, seller_id, quantity)
        return Response(status=HTTP_200_OK)

    def delete(self, request: Request) -> Response:
        """
        Удаляет товар из корзины
        """
        cart = Cart(request)
        product_id = request.data["product_id"]
        cart.remove(product_id)
        return Response(status=HTTP_204_NO_CONTENT)

website/comparison/views.py
from django.http import HttpRequest
from django.views.generic import TemplateView
from rest_framework.permissions import AllowAny
from rest_framework.views import APIView

from . import utils
from .services import ComparisonServices
from .utils import create_categorization


class ComparisonView(TemplateView):
    """
    Представление для отображения страницы сравнения товаров.

    Атрибуты:
        template_name (str): Путь к шаблону, который будет использоваться для отображения.
    """

    template_name = "comparison/comparison.html"

    def get_context_data(self, **kwargs):
        """
        Получает контекст для рендеринга шаблона.

        Параметры:
            **kwargs: Дополнительные параметры, передаваемые в контекст.

        Возвращает:
            dict: Контекст, содержащий товары для сравнения и спецификации категорий.
        """
        context = super().get_context_data(**kwargs)
        user = self.request.user
        unic_spec = self.request.GET.get("unic_spec")
        if user.is_authenticated:
            comparison_products = utils.get_products_with_auth_user(user.pk, unic_spec)
            data = create_categorization(comparison_products[1])

        else:
            comparison_products = utils.get_products_with_unauth_user(self.request, unic_spec)
            data = create_categorization(comparison_products[1], False)
        context["comparison_products"] = data
        context["correct_spec"] = comparison_products[0]
        context["unic_spec"] = True if unic_spec else False
        return context


class ComparisonDeleteApiView(APIView):
    """
    API View для удаления товара из списка сравнения.

    Этот класс обрабатывает DELETE-запросы и вызывает сервисный метод
    для удаления товара из списка сравнения. Доступ к методу разрешен всем
    пользователям, включая неаутентифицированных.

    Атрибуты:
        permission_classes (tuple): Указывает, что доступ разрешен любому пользователю (AllowAny).

    Методы:
        delete(request, *args, **kwargs):
            Обрабатывает DELETE-запрос для удаления товара из списка сравнения.

    Параметры метода delete:
        request (HttpRequest): Объект HTTP-запроса.
        *args: Дополнительные позиционные аргументы.
        **kwargs: Дополнительные именованные аргументы.

    Возвращает:
        Response: HTTP-ответ с результатом операции:
            - Успешный результат удаления.
            - Сообщение об ошибке, если удаление завершилось неудачно.
            - Сообщение о фатальной ошибке в случае исключения.
    """

    permission_classes = (AllowAny,)

    def delete(self, request: HttpRequest, *args, **kwargs):
        try:
            service_answer = ComparisonServices.delete_product_final(request)
            return ComparisonServices.delete_product_answer(service_answer)
        except Exception:
            return ComparisonServices.return_fatal_error()


class ComparisonAddApiView(APIView):
    """
    API View для добавления товара в список сравнения.

    Этот класс обрабатывает POST-запросы и вызывает сервисный метод
    для добавления товара в список сравнения. Доступ к методу разрешен всем
    пользователям, включая неаутентифицированных.

    Атрибуты:
        permission_classes (tuple): Указывает, что доступ разрешен любому пользователю (AllowAny).

    Методы:
        post(request, *args, **kwargs):
            Обрабатывает POST-запрос для добавления товара в список сравнения.

    Параметры метода post:
        request (HttpRequest): Объект HTTP-запроса.
        *args: Дополнительные позиционные аргументы.
        **kwargs: Дополнительные именованные аргументы.

    Возвращает:
        Response: HTTP-ответ с результатом операции:
            - Успешный результат добавления.
            - Сообщение об ошибке, если добавление завершилось неудачно.
            - Сообщение о фатальной ошибке в случае исключения.
    """

    permission_classes = (AllowAny,)

    def post(self, request: HttpRequest, *args, **kwargs):
        try:
            service_answer = ComparisonServices.add_product_final(request)
            return ComparisonServices.add_product_answer(service_answer)
        except Exception:
            return ComparisonServices.return_fatal_error()

website/core/imports/views.py
import logging
import os

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.shortcuts import render

from .tasks import import_products_task

# Создание директории для логов
log_directory = "logs"
if not os.path.exists(log_directory):
    os.makedirs(log_directory)

# Настройка логирования
logging.basicConfig(filename=os.path.join(log_directory, "import.log"), level=logging.INFO)

# Создание директории для загрузок
upload_directory = "uploads"
if not os.path.exists(upload_directory):
    os.makedirs(upload_directory)


def import_products_view(request):
    if request.method == "POST":
        email = request.POST.get("email")

        files = request.FILES.getlist("files")
        if not files:
            files = [f for f in os.listdir(upload_directory) if f.endswith((".json", ".xml"))]

        for file in files:
            file_path = os.path.join(upload_directory, file.name)
            with open(file_path, "wb+") as destination:
                for chunk in file.chunks():
                    destination.write(chunk)

            import_products_task.delay(file_path, email)

        return redirect("success")

    return render(request, "core/import.html")

website/core/templates/core/banner.html
{% load static %}

  <div class="Header-slider">
      <div class="Slider Slider_main">

        <div class="Slider-box">
          {% for banner in random_banner %}

            <div class="Slider-item">
              <div class="Slider-content">
                <div class="row">
                  <div class="row-block">
                    <strong class="Slider-title">{{ banner.manufacturer }}<span class="text_primary"> {{ banner.model }}</span> {{ banner.name }}
                    </strong>
                    <div class="Slider-text">{{ banner.text }}
                    </div>
                    <div class="Slider-footer"><a class="btn btn_primary" href="#">Get Started</a>
                    </div>
                  </div>
                  <div class="row-block">
                    <div class="Slider-img"><img src="{% static 'assets/img/content/home/slider.png' %}" alt="slider.png"/>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>

        <div class="Slider-navigateWrap">
          <div class="Slider-navigate"></div>
        </div>

      </div>
  </div>

website/core/templates/core/header.html
{% load core_tags %}
{% load static %}
{% load catalog_extras %}
{% load i18n %}

<header class="Header">
    <div class="ControlPanel">
        <div class="wrap">
            <div class="row ControlPanel-row">
                <div class="row-block">
                    <div class="row ControlPanel-rowSplit">
                        <div class="row-block hide_700">
                            <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                                <li class="menu-item"><a class="menu-link" href="#"><img
                                        src="{% static 'assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg"/></a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="#"><img
                                        src="{% static 'assets/img/icons/socialHeader/in.svg' %}" alt="in.svg"/></a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="#"><img
                                        src="{% static 'assets/img/icons/socialHeader/pt.svg' %}" alt="pt.svg"/></a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="#"><img
                                        src="{% static 'assets/img/icons/socialHeader/mail.svg' %}" alt="mail.svg"/></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <nav class="row-block">
                    <div class="row ControlPanel-rowSplit">
                        {% if not request.user.is_authenticated %}
                            <div class="row-block">
                                <a class="ControlPanel-title" href="{% url 'custom_auth:login' %}">
                                    {% translate 'Login' %}
                                </a>
                            <a class="ControlPanel-title" href="{% url 'custom_auth:register' %}">{% trans 'Registration' %}</a>
                            </div>
                        {% else %}
                            <div class="row-block">
                                <a class="ControlPanel-title" href="{% url 'custom_auth:personal-cabinet' %}">
                                    {{ request.user.login }}
                                </a>
                            </div>
                        {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!--+div.menuModal#navigate
        //    +menu([
        //        ['Главная','index.html'],
        //        ['Портфолио','index.html'],
        //        ['Мои проекты','index.html'],
        //        ['Контакты','index.html']
        //    ], page === 'article'? 'Портфолио': 'Главная')._main

        block
        -->
    </div>
    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo"><a class="logo" href="{% url 'core:index' %}"><img class="logo-image"
                                                                                                  src="{% static 'assets/img/logo.png' %}"
                                                                                                  alt="logo.png"/></a>
            </div>
            <nav class="row-block row-block_right Header-menu">
                <div class="menuModal" id="navigate">
                    <ul class="menu menu_main">
                        <li class="menu-item"><a class="menu-link" href="{% url 'core:index' %}">{% translate 'Main' %}</a>
                        </li>
                        <li class="menu-item"><span class="menu-label menu-label_success">{% trans 'Discounts' %}</span><a
                                class="menu-link" href="{% url 'catalog:catalog' %}">{% trans 'Catalog' %}</a>
                        </li>
                        <li class="menu-item">
                            <a class="menu-link" href="{% url 'comparison:comparison_page' %}">{% trans 'Comparison' %}</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="row-block">

                <div class="CartBlock">
                    <div class="dropdown">
                        <button class="dropbtn"><img class="CartBlock-img"
                                                     src="{% static 'assets/img/icons/loon-icon.svg' %}"
                                                     alt="loon-icon.svg"/></button>
                        <div class="dropdown-content">
                            {#                            {% if user_is_auth %}#}
                            {% if user.is_authenticated %}
                                <a class="dropdown-content-a" href="{% url 'custom_auth:personal-cabinet' %}">{% trans 'Personal
                                    account' %}</a>

                            <a class="dropdown-content-a" href="{% static 'account.html' %}">{% trans 'Administrative
                                section' %}
                                </a>
                            <form id="logout-form" method="post" action="{% url 'custom_auth:logout' %}"
                                  style="display: none;">
                                {% csrf_token %}
                            </form>
                        {% else %}
                            <a href="{% url 'custom_auth:login' %}">
                                <button class="dropbtn"><img class="CartBlock-img"
                                                             src="{% static 'assets/img/icons/loon-icon.svg' %}"
                                                             alt="loon-icon.svg"/></button>
                            </a>
                            <div class="dropdown-content">
                                <form id="login-form" method="post" action="{% url 'custom_auth:login' %}"
                                      style="display: none;">
                                    {% csrf_token %}
                                </form>
                                <a href="#"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    {% trans 'Logout' %}
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <a class="CartBlock-block" href="{% url 'cart:detail' %}"><img class="CartBlock-img"
                                                                                   src="{% static 'assets/img/icons/cart.svg' %}"
                                                                                   alt="cart.svg"/><span
                            class="CartBlock-amount">0</span></a>
                    <div class="CartBlock-block"><span class="CartBlock-cost">0</span>


                    </div>
                </div>
            </div>
            <div class="row-block Header-trigger"><a class="menuTrigger" href="#navigate">
                <div class="menuTrigger-content">{% trans 'Show navigation' %}
                </div>
                <span></span><span></span><span></span>
            </a>
            </div>
        </div>
    </div>
    <div class="Header-searchWrap">
        <div class="wrap">
            <div class="Header-categories">
                <div class="CategoriesButton">
                    <div class="CategoriesButton-title">
                        <div class="CategoriesButton-icon"><img src="{% static 'assets/img/icons/allDep.svg' %}"
                                                                alt="allDep.svg"/>
                        </div>
                        <span class="CategoriesButton-text">{% trans 'All categories' %}</span>
                        <div class="CategoriesButton-arrow">
                        </div>
                    </div>
                    <div class="CategoriesButton-content">
                        <div class="CategoriesButton-link"><a href="{% url 'discount:active_discounts' %}">
                            <div class="CategoriesButton-icon"><img
                                    src="{% static 'assets/img/icons/departments/4.svg' %}" alt="4.svg"/>
                            </div>
                            <span class="CategoriesButton-text">{% trans 'Discounts' %}!</span>
                        </a>
                        </div>

                        {% get_categories as categories %}
                        {% for category in categories %}
                            <div class="CategoriesButton-link">
                                <a href="{% url 'catalog:catalog' category.id %}">
                                    <div class="CategoriesButton-icon">
                                        {% if category.icon %}
                                            <img src="{{ category.icon.url }}" alt="{{ category.name }}"/>
                                        {% endif %}
                                    </div>
                                    <span class="CategoriesButton-text">{{ category.name }}</span>
                                </a>

                                <div>
                                    {% if category.sub_categories.count > 0 %}
                                        <a class="CategoriesButton-arrow" href="#"></a>
                                        <div class="CategoriesButton-submenu">
                                            {% for sub_category in category.sub_categories.all %}
                                                <a class="CategoriesButton-link"
                                                       href="{% url 'catalog:catalog' sub_category.id %}">
                                                            <div class="CategoriesButton-icon">
                                                                {% if sub_category.icon %}
                                                                    <img src="{{ sub_category.icon.url }}" alt="{{ sub_category.name }}"/>
                                                                {% endif %}
                                                        <div class="CategoriesButton-icon">
                                                            {% if subcategory.icon %}
                                                                <img src="{{ sub_category.icon.url }}"
                                                                     alt="{{ sub_category.name }}"/>
                                                            {% endif %}
                                                        </div>
                                                        <span class="CategoriesButton-text">{{ sub_category.name }}</span>
                                                </a>

                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
            <div class="Header-searchLink"><img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>
            </div>
            <div class="Header-search">
                <div class="search">
                    <form class="form form_search" action="#" method="post">
                        {% csrf_token %}
                        <input class="search-input" id="query" name="query" type="text"
                               placeholder="NVIDIA GeForce RTX 3060"/>
                        <button class="search-button" type="submit" name="search" id="search"><img
                                src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>{% trans 'Search' %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="operation_status_area green_status">
        <div class="status_block">
            <div class="status_header">
                <p></p>
            </div>
            <div class="delete_message">
                <button class="delete_button_status delete_button_status_green"></button>
            </div>
        </div>
        <div class="message_status_block">
            <p></p>
        </div>
    </div>
</header>

website/core/templates/core/import.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Import' %}
{% endblock %}


{% block body %}
<body>
    <h1>{% trans 'Importing a product' %}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br><br>

        <label for="files">{% trans 'Select Files' %}:</label>
        <input type="file" id="files" name="files" multiple><br><br>

        <button type="submit">{% trans 'Import' %}</button>
    </form>
</body>
{% endblock %}